---
name: Geek5
description: Software engineer obsessed with Web technologies
url: http://geek5.cn
baseurl:
permalink: "/blog/:year/:month/:day/:title.html"
paginate_path: "/blog/page:num/"
paginate: 10

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    sectionid: blog
- scope:
    path: blog
    type: pages
  values:
    sectionid: blog

exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- vendor/bundle
#markdown: redcarpet
#redcarpet:
#  extensions:
#  - fenced_code_blocks
#  - footnotes
#highlighter: pygments
markdown:    kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: :compressed
  sass_dir: _css
gems:
- jekyll-redirect-from
- jekyll-paginate

excerpt_separator: "\n\n"
