title: "Geek5==A geek 's 舞zone"
email: hi@geek5.cn
description: "Software engineer obsessed with Web technologies"
baseurl: ""
url: "https://geek5.cn"

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - node_modules

paginate: 6
paginate_path: "/page/:num/"

googleAnalyticsId: UA-87935934-1  

gems:
  - jekyll-paginate

excerpt_separator: <!--more-->

future: true

# Serving
detach:  false
port:    4100
host:    0.0.0.0

# Staticman
staticmanUrl: https://api.staticman.net/v2/entry/calcyu/calcyu.github.io/master/comments